## week3  graded assignment


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
params = np.load('parameters.npz')

In [11]:
params['W1']

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [44]:
def compute_a(x, w,b):
    a = np.dot(w,x) + b
    return a

def compute_sigmoid(a):
    return 1/(1+np.exp(-a))

def compute_softmax(a):
    return np.exp(a)/np.sum(np.exp(a))

def compute_loss(y, y_hat):
    return -np.sum(y*np.log(y_hat))

def compute_graidient_loss(y, y_hat):
    return y_hat - y

def grad_of_softmax(a, grad_loss):
    return grad_loss * a * (1-a)

def grad_of_sigmoid(a, grad_loss):
    return grad_loss * a * (1-a)


def compute_gradient_w(x, grad_loss):
    return np.outer(grad_loss, x)

def compute_updated_w(w, grad_w, learning_rate):
    return w - learning_rate*grad_w

def cross_entroy_loss(y, y_hat):
    return -np.sum(y*np.log(y_hat))

In [26]:
dict_of_neurons = {}
x = np.array([1, 0, 1]).reshape(3, 1)
print(x.shape)
y = np.array([0, 0, 1]).reshape(3, 1)

dict_of_neurons['W1'] = params['W1']
dict_of_neurons['b1'] = params['b1']
dict_of_neurons['W2'] = params['W2']
dict_of_neurons['b2'] = params['b2']
dict_of_neurons['W3'] = params['W3']
dict_of_neurons['b3'] = params['b3']
print(dict_of_neurons.items())

(3, 1)
dict_items([('W1', array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])), ('b1', array([[0.38344152],
       [0.79172504],
       [0.52889492]])), ('W2', array([[0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834]])), ('b2', array([[0.79915856],
       [0.46147936],
       [0.78052918]])), ('W3', array([[0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033]])), ('b3', array([[0.56843395],
       [0.0187898 ],
       [0.6176355 ]]))])


In [33]:
# calculating the value of a1
a1 = np.dot(dict_of_neurons['W1'], x) + dict_of_neurons['b1']
print('value of a1 is:', np.sum(a1))

value of a1 is: 5.44766562448759


In [34]:
h1 = compute_sigmoid(a1)
np.sum(h1)

2.5749524957231924

In [42]:
a2 = dict_of_neurons['W2'] @ h1 + dict_of_neurons['b2']
h2 = compute_sigmoid(a2)
a3 = dict_of_neurons['W3'] @ h2 + dict_of_neurons['b3']
y_hat = compute_softmax(a3)
v = round(np.sum(a2), 1)
print(v)
print(f'value of a2: {round(np.sum(a2), 1)} and value of h2: {round(np.sum(h2), 2)} and value of a3: {(np.sum(a3), 2)} and value of y_hat: {y_hat}')
# sanity check
# assert(round(np.sum(a2), 1) == 6.4)
# assert(round(np.sum(h2), 2) == 2.63)
# assert(round(np.sum(a3), 2) == 4.87)
print('value of y_hat is:', y_hat)

6.5
value of a2: 6.5 and value of h2: 2.63 and value of a3: (4.874920988265704, 2) and value of y_hat: [[0.23691422]
 [0.33838847]
 [0.42469732]]
value of y_hat is: [[0.23691422]
 [0.33838847]
 [0.42469732]]


In [45]:
# cross entropy loss of the following function is:
loss = cross_entroy_loss(y, y_hat)
print('cross entropy loss is:', loss)

cross entropy loss is: 0.8563785622753882


In [54]:
grad_of_loss  = compute_graidient_loss(y, y_hat)
print('grad_h3:', grad_of_loss)

grad_h3: [[ 0.23691422]
 [ 0.33838847]
 [-0.57530268]]


In [55]:
grad_h3 = grad_of_softmax(a3, grad_of_loss)
print('grad_a3:', grad_h3)

grad_a3: [[-0.09681863]
 [-0.37710253]
 [ 0.97614604]]


In [70]:
# loss funtion according to input
loss_y = []
print(y_hat.shape)
for i in range(y_hat.shape[0]):
    l = -(y[i]/y_hat[i])
    loss_y.append(l)
    print(f'loss {i}th:', -(y[i]/y_hat[i]))
grad_h3 = np.array(loss_y).reshape(3, 1)
grad_h3

(3, 1)
loss 0th: [-0.]
loss 1th: [-0.]
loss 2th: [-2.35461813]


array([[-0.        ],
       [-0.        ],
       [-2.35461813]])

In [69]:
grad_a3 = -1*( grad_h3 - y_hat)
grad_a3

array([[0.23691422],
       [0.33838847],
       [2.77931545]])