# Practice Assignment week 7


In [1]:
import numpy as np 
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']
c_vec = CountVectorizer()
text_data_t = c_vec.fit_transform(text_data)
text_data_t.shape

(9, 99)

In [6]:
c_vec.vocabulary_['metaverse']

51

In [7]:
c_vec

CountVectorizer()

In [8]:
c_v_2 = CountVectorizer(min_df= 2)
new_c_v = c_v_2.fit_transform(text_data)
new_c_v.shape

(9, 20)

In [10]:
docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]
doc_cv = c_vec.fit_transform(docs)
print(doc_cv)

  (0, 9)	1
  (0, 3)	1
  (0, 7)	1
  (0, 2)	1
  (0, 5)	1
  (1, 9)	1
  (1, 3)	1
  (1, 7)	1
  (1, 1)	2
  (1, 6)	1
  (2, 9)	1
  (2, 3)	1
  (2, 7)	1
  (2, 0)	1
  (2, 8)	1
  (2, 4)	1


In [15]:
print(doc_cv.toarray())

[[0 0 1 1 0 1 0 1 0 1]
 [0 2 0 1 0 0 1 1 0 1]
 [1 0 0 1 1 0 0 1 1 1]]


In [16]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'list[HashableT] | Callable[[Hashable], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Sequence[str] | Mapping[str, Sequence[str]] | None' = None,
    keep_default_na: 'bool' = True,
    n